spring:
  config:
    import:
        - classpath:yaml/application-local.yml
        - classpath:yaml/application-dev.yml
        - classpath:yaml/application-prod.yml
  application:
    name: bms-batch
  profiles:
    active: local
  batch:
    job:
      enabled: false
      # name: ${job.name:}