
spring:
  application:
    name: bms-batch
  profiles:
    active: local
  batch:
    job:
      enabled: false
      names: ${job.name:NONE}

# ADDED: Batch job related properties
batch:
  job:
    bms-txt-file:
      input-path: /Users/smkim/intellij/bms_batch/ # ??? ??? ?? ?? ??
      file-pattern: "*.txt" # ??? ?? ??

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  batch:
    jdbc:
      initialize-schema: never
  main:
    allow-bean-definition-overriding: true

mybatis:
  type-aliases-package: tmoney.tnz.bmsbatch.domain
  mapper-locations: classpath:mapper/*.xml